defaults:
  - env: dmc_vision
  - model: size12M
  # Disable Hydra's Python logging-to-file (train.log)
  - override hydra/job_logging: disabled
  - _self_

logdir: logdir/${now:%Y-%m-%d}/${now:%H-%M-%S}
seed: 0
deterministic_run: False
device: 'cuda:0'

hydra:
  run:
    dir: ${logdir}

batch_size: 16
batch_length: 64

buffer:
  batch_size: ${batch_size}
  batch_length: ${batch_length}
  max_size: 5e5
  device: ${device}
  storage_device: 'cuda:0'

trainer:

  steps: 100000

  batch_per_gpu: 4

  batch_length: 64

  checkpoint_every: 500

  log_every: 50

  num_workers: 4

  augmentation:

    noise_std: 0.05

    use_flip: true

    use_brightness: true

    brightness_std: 0.1

    use_cutout: false

    cutout_size: 32

dataset:

  segment_dir: /kaggle/input/fpv-segments
